project_id = "ndghbgkcpjfevkygfxds"

[functions.sav-classify-business]
verify_jwt = false

[functions.sav-sync-experts]
verify_jwt = false

[functions.sav-telegram-auth]
verify_jwt = false

[functions.sav-sync-clients]
verify_jwt = false

[functions.sav-ai-search-clients]
verify_jwt = false

[functions.sav-send-telegram-message]
verify_jwt = false

[functions.sav-sync-telegram-profile]
verify_jwt = false

[functions.sav-notify-expert-selection]
verify_jwt = false

[functions.sav-sync-cities]
verify_jwt = false

[functions.sav-ai-match-experts]
verify_jwt = false

[functions.sav-ai-recommend-tariff]
verify_jwt = false

[functions.sav-notify-tariff-selection]
verify_jwt = false
